# Generated by Django 4.2.7 on 2023-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0002_rename_sudent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='departent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollnumber',
        ),
        migrations.AddField(
            model_name='student',
            name='Age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Phonenumber',
            field=models.IntegerField(default=983489237498),
        ),
    ]
